pipeline {
    agent any
    parameters {
        choice(choices: ['QA', 'DEMO','PROD'], description: 'Which AWS account do you want to use?', name: 'ACCOUNT')
        credentials (name: 'Credentials',description: 'Credentials for all accounts')
    }
    stages {
        stage('Example') {
            steps {
                sh 'printenv'
            }
        }
    }
}