pipeline {
    agent any

    stages {
        stage('Example') {
            steps {               
                //sh 'docker run -v ${pwd}:/src ubuntu /src/epigenome-dev.sh'
               sh 'pwd'
               sh 'ls'
            }
        }
    }
}