pipeline {
    agent any
    parameters {
        choice(choices: ['DEV','QA','DEMO','PROD'], description: 'Which AWS account do you want to use?', name: 'ACCOUNT')
        choice(choices: ['EU (EU-WEST-1)', 'US (US-WEST-2)'], description: 'Which AWS region do you want to use?', name: 'REGIONS')
        credentials (name: 'Credentials',description: 'Credentials for all accounts')
    }
    stages {
        stage('Example') {
            steps {
                sh 'printenv'
            }
        }
    }
}